# Generated by Django 2.2 on 2021-10-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='descripion',
            new_name='description',
        ),
    ]
